# Generated by Django 3.1.7 on 2021-03-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='idade_minima',
            field=models.IntegerField(default=15),
        ),
    ]
